name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image and run tests
        run: |
          docker compose build
          docker compose run backend pytest

          docker compose up -d
          docker compose down

  push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: git_sha
        run: echo "GIT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Build and Push Docker Backend Image
        run: |
          docker build -t ghcr.io/sverrenystad/eit-backend:${{ env.GIT_SHA }} ./backend
          docker push ghcr.io/sverrenystad/eit-backend:${{ env.GIT_SHA }}

      - name: Build and Push Docker client Image
        run: |
          docker build -t ghcr.io/sverrenystad/eit-client:${{ env.GIT_SHA }} .client/
          docker push ghcr.io/sverrenystad/eit-client:${{ env.GIT_SHA }}